#!/bin/bash

# GitHub Secrets 配置助手
# 此脚本帮助你生成配置 GitHub Secrets 所需的信息

echo "=========================================="
echo "GitHub Secrets 配置信息"
echo "=========================================="
echo ""

echo "📋 需要在 GitHub 仓库中添加以下 4 个 Secrets："
echo ""

echo "1️⃣  Secret 名称: SERVER_HOST"
echo "   说明: 腾讯云服务器的公网 IP 地址"
echo "   示例值: 123.45.67.89"
echo "   👉 你的值: [请输入你的服务器 IP]"
echo ""

echo "2️⃣  Secret 名称: SERVER_USER"
echo "   说明: SSH 登录用户名"
echo "   示例值: root 或 ubuntu"
echo "   👉 你的值: [通常是 root]"
echo ""

echo "3️⃣  Secret 名称: SERVER_SSH_KEY"
echo "   说明: SSH 私钥完整内容"
echo "   👉 获取方式："
echo ""
echo "   方法 1 - 如果你已有 SSH 密钥："
echo "   cat ~/.ssh/id_rsa"
echo ""
echo "   方法 2 - 生成新的 SSH 密钥："
echo "   ssh-keygen -t rsa -b 4096 -C 'deploy@github-actions'"
echo "   cat ~/.ssh/id_rsa"
echo ""
echo "   ⚠️  注意：复制时包含 '-----BEGIN RSA PRIVATE KEY-----' 和 '-----END RSA PRIVATE KEY-----'"
echo ""

echo "4️⃣  Secret 名称: SERVER_PORT"
echo "   说明: SSH 端口号"
echo "   示例值: 22"
echo "   👉 你的值: 22 (默认)"
echo ""

echo "=========================================="
echo "配置步骤"
echo "=========================================="
echo ""
echo "1. 访问: https://github.com/JERSONLEIBOY/express-mongodb-backend-api/settings/secrets/actions"
echo ""
echo "2. 点击 'New repository secret' 按钮"
echo ""
echo "3. 依次添加上面 4 个 Secrets（Name 和 Value）"
echo ""
echo "4. 添加完成后，回到终端继续下一步"
echo ""

echo "=========================================="
echo "SSH 公钥配置（必须操作）"
echo "=========================================="
echo ""
echo "⚠️  重要：需要将 SSH 公钥添加到服务器"
echo ""
echo "获取公钥："
echo "cat ~/.ssh/id_rsa.pub"
echo ""
echo "添加到服务器："
echo "ssh-copy-id root@你的服务器IP"
echo ""
echo "或手动添加："
echo "ssh root@你的服务器IP"
echo "mkdir -p ~/.ssh"
echo "echo '你的公钥内容' >> ~/.ssh/authorized_keys"
echo "chmod 600 ~/.ssh/authorized_keys"
echo ""

echo "=========================================="
echo "验证 SSH 连接"
echo "=========================================="
echo ""
echo "配置完成后，测试 SSH 连接："
echo "ssh -i ~/.ssh/id_rsa root@你的服务器IP"
echo ""
