name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /opt/express-mongodb-backend-api
            sudo git fetch origin
            sudo git reset --hard origin/main

            # 从 template 生成生产配置
            sudo cp .env.production.template .env.production
            sudo sed -i "s|<SERVER_URL>|${{ secrets.SERVER_URL }}|g" .env.production
            sudo sed -i "s|<JWT_SECRET>|${{ secrets.JWT_SECRET }}|g" .env.production
            sudo sed -i "s|<CORS_ORIGIN>|${{ secrets.CORS_ORIGIN }}|g" .env.production
            sudo sed -i "s|<MONGO_ROOT_USERNAME>|${{ secrets.MONGO_ROOT_USERNAME }}|g" .env.production
            sudo sed -i "s|<MONGO_ROOT_PASSWORD>|${{ secrets.MONGO_ROOT_PASSWORD }}|g" .env.production

            sudo docker compose up -d --build
            sudo docker image prune -f